SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'riesgo', 'risk');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'perro', 'dog');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'caballo', 'horse');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'consejo', '(piece of) advice');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'ejercicio', 'exercise');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'rgimen', 'diet');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'peligro', 'danger');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'pan', 'bread');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'vino', 'wine');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'diente', 'tooth');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'ftbol', 'football');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'deporte', 'sport');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'vaso', '(drinking) glass');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'accidente', 'accident');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'cuidado', 'care, carefulness');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'huevo', 'egg');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'azcar', 'sugar');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'baile', 'dance');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'desayuno', 'breakfast');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'pescado', 'fish');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'pollo', 'chicken');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'estrs', 'stress');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'tomate', 'tomato');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'baloncesto', 'basketball');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'bocadillo', 'sandwich');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'caramelo', 'sweet');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'gimnasio', 'gym');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'jamn', 'ham');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'morir', '(to) die | dying');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'caer; caerse', '(to) fall | falling; (to) fall over | falling over');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'cambiar; cambiarse', '(to) change | changing; (to) get changed | getting changed');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'correr', '(to) run | running');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'comer', '(to) eat | eating');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'levantar; levantarse', '(to) raise | raising; (to) get up | getting up');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'jugar', '(to) play (sport/game) | playing (sport/game)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'juego', '(I) play | (I) am playing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'juegas', '(you) play | (you) are playing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'juega | ijuega!', '(she, he, it, one) plays | (she, he, it, one) is playing | (you (sing formal)) play | Play! (you (sing informal))');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'juegan', '(they) play | (they) are playing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'dormir; dormirse', '(to) sleep | sleeping; (to) fall asleep | falling asleep');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'participar', '(to) participate | participating');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'apoyar', '(to) support | supporting');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'cuidar', '(to) take care of | taking care of');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'costar', '(to) cost, be hard | costing, being hard');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'probar', '(to) taste, try | tasting, trying');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'beber', '(to) drink | drinking');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'bailar', '(to) dance I dancing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'montar', '(to) ride, set up I riding, setting up');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'doler', '(to) hurt, be painful I hurting, being painful');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'lavar; lavarse', '(to) wash I washing; (to) have a wash | having a wash');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'descansar', '(to) rest, relax I resting, relaxing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'respirar', '(to) breathe I breathing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'fumar', '(to) smoke I smoking');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'cenar', '(to) have dinner, tea (evening meal) | having dinner, tea (evening meal)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'nadar', '(to) swim | swimming');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'v', 'entrenar; entrenarse', '(to) train | training; (to) train, go training | training, going training');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m/f)', 'joven', 'teenager, young person');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m/f)', 'mdico', 'doctor');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m/f)', 'paciente', 'patient');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'gay', 'gay');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'grande', 'big, large (m, f) (post-noun)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'pequeo', 'little, small, young');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'espaol', 'Spanish');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'largo', 'long');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'negro', 'black');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'blanco', 'white');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'rico', 'rich, wealthy, tasty');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'joven', 'young');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'fuerte', 'strong');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'menor', 'younger, youngest');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'pobre', 'poor, unfortunate (pre-noun), without money (post-noun)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'rojo', 'red');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'francs', 'French');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'ingls', 'English');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'responsable', 'responsible');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'fsico', 'physical');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'cubano', 'Cuban');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'europeo', 'European');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'duro', 'hard, resilient');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'alemn', 'German');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'azul', 'blue');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'verde', 'green');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'religioso', 'religious');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'mexicano', 'Mexican');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'serio', 'serious');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'civil', 'civil');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'bonito', 'pretty, nice, beautiful');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'trabajador', 'hardworking');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'hermoso', 'beautiful, handsome');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'famoso', 'famous, well-known');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'optimista', 'optimistic');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'cristiano', 'Christian');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'argentino', 'Argentinian');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'muerto', 'dead');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'italiano', 'Italian');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'independiente', 'independent, self-sufficient');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'tradicional', 'traditional');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'britnico', 'British');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'musical', 'musical');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'adj', 'chino', 'Chinese');