SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'comer', '(to) eat | eating');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'comprar', '(to) buy, purchase | buying, purchasing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'pagar', '(to) pay (for) | paying (for)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'vender', '(to) sell |selling');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'costar', '(to) cost, be hard | costing, being hard');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'visitar', '(to) visit | visiting');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'viajar', '(to) travel | travelling');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'disfrutar', '(to) enjoy | enjoying');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'probar', '(to) taste, try | tasting, trying');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'conducir', '(to) drive | driving');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'coger', '(to) take, take hold of, catch | taking, taking hold of, catching');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'organizar', '(to) organise | organising');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'soar', '(to) dream I dreaming');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'comunicar', '(to) communicate  I  communicating');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'montar', '(to) ride, set up I riding, setting up');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'practicar', '(to) practise I practising');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'descansar', '(to) rest, relax I resting, relaxing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'llover', '(to) rain I raining');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'reservar', '(to) book, reserve | booking, reserving');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'nadar', '(to) swim | swimming');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj/adv', 'rpido', 'quick, fast');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m/f)', 'mar', 'sea');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m/f)', 'turista', 'tourist');