SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'disear', '(to) design I designing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'repasar', '(to) revise, review | revising, reviewing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'profesor', 'teacher');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'compaero', 'classmate, group member, colleague, companion');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'director', 'headteacher, director, manager');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'polica', 'police, police officer (m)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'mdico', 'doctor');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'modelo', 'model');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'jefe', 'boss, manager, leader');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'estudiante', 'student');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'artista', 'artist, performer');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'escritor', 'writer');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'cliente', 'client, customer');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'abogado', 'lawyer');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'periodista', 'journalist');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'secretario', 'secretary');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'cientfico', 'scientist');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'pintor', 'painter');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'ingeniero', 'engineer');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'msico', 'musician');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'cantante', 'singer');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m/f)', 'influencer', 'influencer');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'rico', 'rich, wealthy, tasty');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'fuerte', 'strong');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'responsable', 'responsible');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'fsico', 'physical');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'serio', 'serious');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'optimista', 'optimistic');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'enfermo', 'ill, sick');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'muerto', 'dead');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'activo', 'active');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'peligroso', 'dangerous');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'cansado', 'tired, tiring');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'dulce', 'sweet');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'dbil', 'weak');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'sano', 'healthy, wholesome');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'deportivo', 'sporty, sports');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'equilibrado', 'balanced');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'vegano', 'vegan');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'adj', 'vegetariano', 'vegetarian');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'mwp', 'patatas fritas', 'chips, fries');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'mwp', 'estar en forma', 'to be fit');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'mwp', 'dar un paseo', '(to) go for a walk, stroll | going for a walk, stroll');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'vida', 'life');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'mano', 'hand');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'agua', 'water');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'cabeza', 'head (body part)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'sociedad', 'society');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'carrera', 'career, (university) degree course, race');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'enfermedad', 'illness, disease');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'salud', 'health');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'energa', 'energy, power');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'piel', 'skin');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'carne', 'meat');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'comida', 'food, meal, lunch');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'costumbre', 'custom, habit, tradition');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'opcin', 'option, choice');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'hambre', 'hunger');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'juventud', 'youth');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'leche', 'milk');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'medicina', 'medicine');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'copa', 'cup, glass');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'droga', 'drug');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'botella', 'bottle');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'fruta', 'fruit');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'sed', 'thirst');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'dieta', 'diet');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'cena', 'dinner, evening meal');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'grasa', 'fat, grease');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'bebida', 'drink');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'naranja', 'orange (fruit)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'manzana', 'apple');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'sal', 'salt');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'verdura', 'vegetable');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'ensalada', 'salad');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'hamburguesa', 'burger');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'uva', 'grape');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'paella', 'paella (dish usually of rice and seafood)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (f)', 'bicicleta, bici', 'bicycle, bike');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (fpl)', 'tapas', 'small dishes of food, bar snacks');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'caf', 'coffee, cafe');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'ojo', 'eye');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'amigo', 'friend');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'cuerpo', 'body');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'amor', 'love');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'partido', '(sports) match, (political) party');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'hermano', 'brother');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'campo', 'countryside, pitch, field');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'juego', 'game');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'pie; a pie', 'foot; on foot');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'equipo', 'team, equipment');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'sol', 'sun');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'producto', 'product');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'aire', 'air');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'artculo', 'article, product, item');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'sueo', 'dream, sleep');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'corazn', 'heart');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'peso', 'weight, peso (currency)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'miembro', 'member');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Healthy living and lifestyle', 'n (m)', 'pelo', 'hair');