SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'fbrica', 'factory');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'basura', 'rubbish, junk');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'primavera', 'spring');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'contaminacin', 'pollution');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'geografa', 'geography');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'recepcin', 'reception');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'piscina', 'swimming pool');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'desventaja', 'disadvantage');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'mezquita', 'mosque');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'sinagoga', 'synagogue');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'corrida', 'bullfight');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'Espaa', 'Spain');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'Sudamrica', 'South America');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'bicicleta, bici', 'bicycle, bike');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (fpl)', 'afueras', 'outskirts, suburbs');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'animal', 'animal');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'caf', 'coffee, cafe');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'camping', 'camp site, camping');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'sur', 'south');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'este', 'east');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'tiempo', 'time (general), weather');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'pas', 'country');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'mundo', 'world');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'lugar', 'place, position');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'problema', 'problem');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'pueblo', 'village, small town');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'estudio', 'study, learning, studio');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'efecto', 'effect');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'centro', 'centre, middle');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'cambio; en cambio', 'change; on the other hand, whereas');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'campo', 'countryside, pitch, field');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'pie; a pie', 'foot; on foot');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'proyecto', 'project, plan');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'sol', 'sun');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'papel', 'paper, role, part');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'producto', 'product');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'aire', 'air');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'espacio', 'space, room');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'uso', 'use');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'sitio (web)', 'place, site (website)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'mercado', 'market');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'ro', 'river');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'esfuerzo', 'effort');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'cielo', 'sky, heaven');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'norte', 'north');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'colegio', '(secondary) school');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'tamao', 'size, dimension');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'cuarto', 'quarter (used in time expressions), room');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'banco', '(financial) bank, bench');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'rbol', 'tree');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'extranjero', 'abroad, foreigner (m)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'metro', 'underground, tube, metro, metre');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'viento', 'wind');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'edificio', 'building');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'fuego', 'fire');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'piso', 'flat, apartment, floor (of building)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'barrio', 'neighborhood, district');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'calor', 'heat, hot');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'cine', 'cinema');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'grado', 'degree (temperature)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'puesto', 'post, position, stall (market)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'ruido', 'noise');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'hospital', 'hospital');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'olor', 'smell, odour');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'puerto', 'port, harbour');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'museo', 'museum');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'habitante', 'local (person), inhabitant');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'verano', 'summer');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'hotel', 'hotel');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'peligro', 'danger');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'coche', 'car');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'jardn', 'garden');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'patio', 'yard, playground');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'dueo', 'owner, landlord (m)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'dao', 'harm, damage');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'bao', 'bathroom');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'parque', 'park');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'avin', 'plane, aeroplane');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'transporte', 'transport');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'bosque', 'forest, wood');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'tren', 'train');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'kilmetro', 'kilometer');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'instituto', 'secondary school');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'pjaro', 'bird');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'delito', 'crime');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'accidente', 'accident');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'clima', 'climate');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'reloj', 'clock, watch');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'paisaje', 'landscape');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'puente', 'bridge, long weekend');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'saln', 'living room');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'invierno', 'winter');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'plstico', 'plastic');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'templo', 'temple');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'trfico', 'traffic');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'dormitorio', 'bedroom');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'oeste', 'west');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'aeropuerto', 'airport');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'castillo', 'castle');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'estadio', 'stadium');