SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'actividad', 'activity');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'accin', 'action, act');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'vista', 'view, sight');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'serie', 'series');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'cultura', 'culture');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'carrera', 'career, (university) degree course, race');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'organizacin', 'organisation');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'pelcula', 'film, movie');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'carta', 'letter, menu');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'naturaleza', 'nature');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'novela', 'novel');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'red (Red)', 'network (Internet), net (fishing)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'entrada', 'entrance, admission ticket');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'ropa', 'clothes, clothing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'fiesta', 'party, festival');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'tele, televisin', 'TV, television');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'carne', 'meat');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'cmara', 'camera');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'comida', 'food, meal, lunch');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'revista', 'magazine');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'letra', 'letter, lyrics');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'cancin', 'song');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'app', 'app');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'tecnologa', 'technology');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'caja', 'box, till (in shop)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'escena', 'scene (of film), stage');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'violencia', 'violence');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'risa', 'laugh');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'opcin', 'option, choice');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'cocina', 'kitchen, cooking, food technology');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'marca', 'make, brand');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'temporada', 'season (of sport, music)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'leche', 'milk');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'moda; de moda', 'fashion; in fashion, fashionable');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'playa', 'beach');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'copa', 'cup, glass');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'tienda', 'shop, tent');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'bolsa', 'bag');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'compra(s)', 'shopping');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'oferta', 'offer');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'camisa', 'shirt');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'fruta', 'fruit');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'tarjeta', 'written card, bank card');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'cena', 'dinner, evening meal');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'grasa', 'fat, grease');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'guitarra', 'guitar');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'falda', 'skirt');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'bebida', 'drink');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'ficcin', 'fiction');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'naranja', 'orange (fruit)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'manzana', 'apple');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'camiseta', 't-shirt');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'sal', 'salt');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'verdura', 'vegetable');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'piscina', 'swimming pool');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'excursin', 'trip, excursion');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'camarera', 'waitress');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'ensalada', 'salad');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'hamburguesa', 'burger');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'mochila', 'rucksack, school bag');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'telerrealidad', 'reality TV');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'uva', 'grape');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'corrida', 'bullfight');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'paella', 'paella (dish usually of rice and seafood)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'bicicleta, bici', 'bicycle, bike');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (fpl)', 'gafas', 'glasses');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (fpl)', 'tapas', 'small dishes of food, bar snacks');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'caf', 'coffee, cafe');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'camping', 'camp site, camping');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'club', 'club');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'euro', 'euro');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'Internet', 'internet');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'arte', 'art');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'amigo', 'friend');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'libro', 'book');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'partido', '(sports) match, (political) party');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'programa', 'programme');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'traje', 'suit, costume');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'juego', 'game');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'pie; a pie', 'foot; on foot');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'equipo', 'team, equipment');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'sol', 'sun');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'papel', 'paper, role, part');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'producto', 'product');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'aire', 'air');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'artculo', 'article, product, item');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'resultado', 'result');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'viaje', 'trip, journey');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'peso', 'weight, peso (currency)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'miembro', 'member');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'precio', 'price, cost, value');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'personaje', 'character (in book, film)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'teatro', 'theatre, drama');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'tamao', 'size, dimension');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'riesgo', 'risk');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'perro', 'dog');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'caballo', 'horse');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'cine', 'cinema');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'peridico', 'newspaper');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'instrumento', 'instrument');