SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'peor*', 'worse, worst');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'verde', 'green');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'histrico', 'historic, historical');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'moderno', 'modern');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'bonito', 'pretty, nice, beautiful');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'fro', 'cold');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'tranquilo', 'calm, tranquil, relaxed');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'muerto', 'dead');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'seco', 'dry');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'industrial', 'industrial');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'elctrico', 'electric');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'fresco', 'fresh, cool');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'peligroso', 'dangerous');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'vaco', 'empty, vacant');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'limpio', 'clean');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'justo', 'fair, just');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'caliente', 'hot, warm');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'sucio', 'dirty');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'prctico', 'practical, useful');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'feo', 'ugly');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'ideal', 'ideal');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'animado', 'lively');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adv', 'Àdnde?', 'where?');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adv', 'all', 'there, over there');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adv', 'peor**', 'worse');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adv', 'lejos', 'far (away)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adv', 'cerca', 'close, near, nearby');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adv', 'detrs', 'behind');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'mwp', 'centro comercial', 'shopping centre');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'mwp', 'al aire libre', 'in the open air, outdoors');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'mwp', 'cambio climtico', 'climate change');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'casa', 'house');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'ciudad', 'city, town');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'historia', 'history, story');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'agua', 'water');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'tierra', 'earth, land, ground');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'calle', 'street');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'puerta', 'door');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'luz', 'light, electricity');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'empresa', 'company, business, firm');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'informacin', 'information');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'sociedad', 'society');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'zona', 'area, zone');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'universidad', 'university');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'accin', 'action, act');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'vista', 'view, sight');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'iglesia', 'church');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'falta', 'lack, shortage, mistake');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'especie', 'species');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'comunidad', 'community');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'mesa', 'table');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'organizacin', 'organisation');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'diferencia', 'difference');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'regin', 'region');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'capital', 'capital (city)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'causa', 'cause');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'cama', 'bed');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'direccin', 'address, direction');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'energa', 'energy, power');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'naturaleza', 'nature');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'ventana', 'window');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'ciencias', 'science(s)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'flor', 'flower');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'economa', 'economy, economics');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'entrada', 'entrance, admission ticket');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'planta', 'plant, floor');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'pared', '(interior) wall');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'ayuda', 'help');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'plaza', 'square');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'isla', 'island');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'tele, televisin', 'TV, television');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'costa', 'coast');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'estrella', 'star');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'lluvia', 'rain');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'industria', 'industry');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'habitacin', 'room, bedroom');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'oficina', 'office');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'caja', 'box, till (in shop)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'violencia', 'violence');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'salida', 'exit, departure');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'cocina', 'kitchen, cooking, food technology');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'hambre', 'hunger');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'silla', 'chair, seat');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'temperatura', 'temperature');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'izquierda', 'left');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'ventaja', 'advantage, benefit');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'estacin', 'station, season (of the year)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'montaa', 'mountain');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'medicina', 'medicine');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'playa', 'beach');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'tienda', 'shop, tent');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'esquina', '(street) corner');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'derecha', 'right');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'bolsa', 'bag');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'biblioteca', 'library');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'arquitectura', 'architecture');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'compra(s)', 'shopping');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'carretera', 'road');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'escalera', 'stairs, ladder');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (f)', 'instalacin', 'facility');