SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'conocer', '(to) know (person, place), meet (for the first time) | knowing (person, place), meeting (for the first time)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'morir', '(to) die | dying');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'permitir; permitirse', '(to) allow, permit | allowing, permitting; (to) afford | affording');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'entender; entenderse', '(to) understand | understanding; (to) get on | getting on');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'nacer', '(to) be born | being born');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'casarse', '(to) get married| getting married');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'apoyar', '(to) support | supporting');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'gritar', '(to) shout | shouting');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'romper', '(to) break | breaking');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'cuidar', '(to) take care of | taking care of');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'separar; separarse', '(to) separate I separating; (to) separate (of a couple) | separating (of a couple)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'celebrar; celebrarse', '(to) celebrate | celebrating; (to) hold (an event) | holding (an event)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'proteger', '(to) protect | protecting');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'respetar', '(to) respect I respecting');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'comunicar', '(to) communicate  I  communicating');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'discutir', '(to) argue, discuss I arguing, discussing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'besar', '(to) kiss I kissing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'criticar', '(to) criticise | criticising');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'pelearse', '(to) fight (physically) I fighting (physically)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'v', 'divorciarse', '(to) get divorced | getting divorced');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'n (m/f)', 'compaero', 'classmate, group member, colleague, companion');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'n (m/f)', 'estudiante', 'student');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'n (m/f)', 'vecino', 'neighbour');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Identity and relationships', 'n (m/f)', 'paciente', 'patient');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'nico', 'only (m) (pre-noun), unique (post-noun)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'pblico', 'public, audience');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'rico', 'rich, wealthy, tasty');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'joven', 'young');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'especial', 'special');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'ingls', 'English');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'cultural', 'cultural');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'conocido', 'known, well-known');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'popular', 'popular');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'famoso', 'famous, well-known');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'muerto', 'dead');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'musical', 'musical');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'artstico', 'artistic');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'peligroso', 'dangerous');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'casado', 'married');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'gracioso', 'funny');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'guapo', 'good-looking');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'soltero', 'single, unmarried');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'adj', 'online', 'online');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'mwp', 'medios de comunicacin', 'media');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'mwp', 'pasarlo bien/mal', 'to have a good/bad time');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'familia', 'family');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'voz', 'voice');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'relacin', 'relationship');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'msica', 'music');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'sociedad', 'society');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'imagen', 'image, picture');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'serie', 'series');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'cultura', 'culture');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'carrera', 'career, (university) degree course, race');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'pelcula', 'film, movie');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'novela', 'novel');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'red (Red)', 'network (Internet), net (fishing)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'fiesta', 'party, festival');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'tele, televisin', 'TV, television');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'foto', 'photo, picture');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'pareja', 'couple, partner');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'revista', 'magazine');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'estrella', 'star');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'letra', 'letter, lyrics');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'cancin', 'song');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'industria', 'industry');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'marca', 'make, brand');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'moda; de moda', 'fashion; in fashion, fashionable');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'personalidad', 'personality, celebrity');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'entrevista', 'interview');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'droga', 'drug');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'identidad', 'identity');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'guitarra', 'guitar');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'actriz', 'actor (f), actress');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (f)', 'telerrealidad', 'reality TV');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'club', 'club');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'Internet', 'internet');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'nombre', 'name');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'pas', 'country');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'mundo', 'world');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'hijo', 'son, child (m)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'padre; padres', 'father; parents');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'nio', 'child, little boy');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'grupo', 'group');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'arte', 'art');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'libro', 'book');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'amor', 'love');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'hermano', 'brother');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'programa', 'programme');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'juego', 'game');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'dinero', 'money');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'equipo', 'team, equipment');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'proyecto', 'project, plan');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'papel', 'paper, role, part');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'sueo', 'dream, sleep');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'autor', 'writer, author');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'miembro', 'member');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'personaje', 'character (in book, film)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'teatro', 'theatre, drama');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'xito', 'success');