SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'riesgo', 'risk');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'error', 'error, mistake');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'peligro', 'danger');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'vdeo', 'video');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'correo (electrnico)', 'mail, post (email)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'anuncio', 'advert');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'mvil', 'mobile phone');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'seguidor', 'follower');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'ordenador', 'computer');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'teclado', 'keyboard');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'videojuego', 'computer game');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'llamar; llamarse', '(to) call, name | calling, naming; (to) be called | being called');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'buscar', '(to) look for, fetch | looking for, fetching');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'jugar', '(to) play (sport/game) | playing (sport/game)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'juego', '(I) play | (I) am playing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'juegas', '(you) play | (you) are playing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'juega | ijuega!', '(she, he, it, one) plays | (she, he, it, one) is playing | (you (sing formal)) play | Play! (you (sing informal))');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'juegan', '(they) play | (they) are playing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'subir', '(to) go up, upload | going up, uploading');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'descubrir', '(to) discover | discovering');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'bajar', '(to) go down, get off, download, lower  | going down, getting off, downloading, lowering');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'compartir', '(to) share | sharing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'mandar', '(to) send, order | sending, ordering');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'guardar', '(to) keep, save | keeping, saving');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'enviar', '(to) send | sending');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'romper', '(to) break | breaking');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'funcionar', '(to) function, work | functioning, working');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'proteger', '(to) protect | protecting');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'comunicar', '(to) communicate  I  communicating');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'robar', '(to) rob, steal I robbing, stealing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'encender', '(to) turn on I turning on');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'grabar', '(to) record I recording');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'apagar', '(to) turn off, extinguish I turning off, extinguishing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'v', 'votar', '(to) vote I voting');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj/adv', 'rpido', 'quick, fast');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m/f)', 'joven', 'teenager, young person');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m/f)', 'influencer', 'influencer');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'espaol', 'Spanish');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'francs', 'French');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'ingls', 'English');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'cubano', 'Cuban');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'cultural', 'cultural');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'europeo', 'European');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'conocido', 'known, well-known');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'alemn', 'German');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'histrico', 'historic, historical');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'mexicano', 'Mexican');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'hermoso', 'beautiful, handsome');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'famoso', 'famous, well-known');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'fro', 'cold');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'directo', 'direct, straight');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'argentino', 'Argentinian');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'tranquilo', 'calm, tranquil, relaxed');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'clsico', 'classic, classical');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'italiano', 'Italian');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'britnico', 'British');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'industrial', 'industrial');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'chino', 'Chinese');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'fresco', 'fresh, cool');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'colombiano', 'Colombian');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'limpio', 'clean');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'caliente', 'hot, warm');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'chileno', 'Chilean');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'perdido', 'lost');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'barato', 'cheap');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'caro', 'expensive');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'animado', 'lively');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'adj', 'bienvenido', 'welcome');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'mwp', 'patatas fritas', 'chips, fries');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'mwp', 'tomar el sol', '(to) sunbathe | sunbathing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'mwp', 'pasarlo bien/mal', 'to have a good/bad time');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'mwp', 'centro comercial', 'shopping centre');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'mwp', 'dar un paseo', '(to) go for a walk, stroll | going for a walk, stroll');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'historia', 'history, story');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'familia', 'family');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'zona', 'area, zone');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'vista', 'view, sight');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'iglesia', 'church');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'cultura', 'culture');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'comunidad', 'community');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'regin', 'region');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'capital', 'capital (city)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'lengua', 'tongue, language');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'entrada', 'entrance, admission ticket');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'planta', 'plant, floor');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'ropa', 'clothes, clothing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'fiesta', 'party, festival');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'plaza', 'square');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'isla', 'island');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'carne', 'meat');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'foto', 'photo, picture');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'costa', 'coast');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'cmara', 'camera');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'comida', 'food, meal, lunch');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'costumbre', 'custom, habit, tradition');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'lluvia', 'rain');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'vuelta', 'return, trip, ride');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'tradicin', 'tradition');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'salida', 'exit, departure');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'lista', 'list, (school) register');