SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'carcter', 'personality, character');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'cine', 'cinema');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'marido', 'husband');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'famoso', 'celebrity, famous person');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'peridico', 'newspaper');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'instrumento', 'instrument');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'premio', 'prize, reward, award');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'respeto', 'respect, regard');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'matrimonio', 'marriage');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'peligro', 'danger');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'vdeo', 'video');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'novio', 'boyfriend, groom');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'concierto', 'concert');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'actor', 'actor (m)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'comportamiento', 'behaviour');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'espectculo', 'show, spectacle');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'anuncio', 'advert');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m)', 'seguidor', 'follower');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'seguir', '(to) follow I following');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'llamar; llamarse', '(to) call, name | calling, naming; (to) be called | being called');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'leer', '(to) read | reading');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'presentar', '(to) introduce, present | introducing, presenting');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'escuchar', '(to) listen (to) | listening (to)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'ganar', '(to) win, earn | winning, earning');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'tocar', '(to) touch, play (instrument) | touching, playing (instrument)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'jugar', '(to) play (sport/game) | playing (sport/game)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'juego', '(I) play | (I) am playing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'juegas', '(you) play | (you) are playing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'juega | ijuega!', '(she, he, it, one) plays | (she, he, it, one) is playing | (you (sing formal)) play | Play! (you (sing informal))');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'juegan', '(they) play | (they) are playing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'nacer', '(to) be born | being born');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'casarse', '(to) get married| getting married');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'vestir; vestirse', '(to) dress | dressing; (to) get dressed | getting dressed');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'cantar', '(to) sing | singing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'separar; separarse', '(to) separate I separating; (to) separate (of a couple) | separating (of a couple)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'celebrar; celebrarse', '(to) celebrate | celebrating; (to) hold (an event) | holding (an event)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'viajar', '(to) travel | travelling');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'respetar', '(to) respect I respecting');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'bailar', '(to) dance I dancing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'grabar', '(to) record I recording');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'votar', '(to) vote I voting');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'v', 'divorciarse', '(to) get divorced | getting divorced');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m/f)', 'modelo', 'model');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m/f)', 'artista', 'artist, performer');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m/f)', 'escritor', 'writer');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m/f)', 'jugador', 'player');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m/f)', 'pintor', 'painter');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m/f)', 'msico', 'musician');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m/f)', 'cantante', 'singer');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Celebrity culture', 'n (m/f)', 'influencer', 'influencer');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'espaol', 'Spanish');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'especial', 'special');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'ingls', 'English');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'cubano', 'Cuban');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'cultural', 'cultural');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'religioso', 'religious');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'histrico', 'historic, historical');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'mexicano', 'Mexican');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'cristiano', 'Christian');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'argentino', 'Argentinian');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'musical', 'musical');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'catlico', 'Catholic');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'peligroso', 'dangerous');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'colombiano', 'Colombian');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'judo', 'Jewish');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'chileno', 'Chilean');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'divertido', 'fun, enjoyable');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'musulmn', 'Muslim');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'adj', 'animado', 'lively');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'intj', 'ÁEnhorabuena!', 'Congratulations!');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'mwp', 'pasarlo bien/mal', 'to have a good/bad time');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'mwp', 'al aire libre', 'in the open air, outdoors');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'mwp', 'plaza de toros', 'bullring');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'mwp', 'fuegos artificiales', 'fireworks');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'mwp', 'dar un paseo', '(to) go for a walk, stroll | going for a walk, stroll');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'mwp', 'Reyes Magos', 'the Three Kings, the Three Wise Men');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'mwp', 'Da de Reyes', 'Epiphany, 6th January');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'mwp', 'Da de Muertos', 'Day of the Dead (Mexican celebration)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'mwp', 'Semana Santa', 'Easter Week, Holy Week');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'historia', 'history, story');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'calle', 'street');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'luz', 'light, electricity');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'msica', 'music');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'sociedad', 'society');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'vista', 'view, sight');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'iglesia', 'church');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'cultura', 'culture');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'pelcula', 'film, movie');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'regin', 'region');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'capital', 'capital (city)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'lengua', 'tongue, language');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'flor', 'flower');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'ropa', 'clothes, clothing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'fiesta', 'party, festival');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'plaza', 'square');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'comida', 'food, meal, lunch');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'costumbre', 'custom, habit, tradition');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'cancin', 'song');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'tradicin', 'tradition');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'cocina', 'kitchen, cooking, food technology');