SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'adj', 'ingls', 'English');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'adj', 'responsable', 'responsible');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'adj', 'trabajador', 'hardworking');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'adj', 'educativo', 'educational');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'adj', 'laboral', '(of) work, relating to work');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'adj', 'listo', 'ready (after estar), clever, intelligent (after ser)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'adj', 'cansado', 'tired, tiring');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'adj', 'deportivo', 'sporty, sports');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'adj', 'tonto', 'silly');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'adj', 'online', 'online');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'adj', 'perezoso', 'lazy');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'mwp', 'medios de comunicacin', 'media');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'mwp', 'al aire libre', 'in the open air, outdoors');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'historia', 'history, story');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'palabra', 'word');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'relacin', 'relationship');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'puerta', 'door');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'empresa', 'company, business, firm');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'clase', 'class, kind, type, classroom, lesson');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'msica', 'music');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'universidad', 'university');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'experiencia', 'experience');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'escuela', '(primary) school');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'carrera', 'career, (university) degree course, race');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'educacin', 'education');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'mesa', 'table');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'pelcula', 'film, movie');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'oportunidad', 'opportunity, chance');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'lengua', 'tongue, language');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'pgina', 'page');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'carta', 'letter, menu');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'compaa', 'company');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'prueba', 'test, trial, proof');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'suerte', 'luck, fortune');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'ventana', 'window');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'novela', 'novel');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'ciencias', 'science(s)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'red (Red)', 'network (Internet), net (fishing)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'economa', 'economy, economics');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'ropa', 'clothes, clothing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'revista', 'magazine');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'conversacin', 'conversation');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'tarea', 'task, chore, homework');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'industria', 'industry');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'frase', 'phrase, sentence');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'tecnologa', 'technology');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'oficina', 'office');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'caja', 'box, till (in shop)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'presin', 'pressure');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'nota', 'grade, note, mark');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'opcin', 'option, choice');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'lista', 'list, (school) register');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'silla', 'chair, seat');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'regla', 'rule, ruler');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'confianza', 'confidence, trust');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'moda; de moda', 'fashion; in fashion, fashionable');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'medicina', 'medicine');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'amistad', 'friendship');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'profesin', 'profession');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'tienda', 'shop, tent');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'entrevista', 'interview');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'bolsa', 'bag');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'biblioteca', 'library');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'discusin', 'discussion, argument');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'oferta', 'offer');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'instalacin', 'facility');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'camisa', 'shirt');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'fbrica', 'factory');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'vacaciones; de vacaciones', 'holidays; on holiday');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'falda', 'skirt');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'actriz', 'actor (f), actress');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'geografa', 'geography');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'recepcin', 'reception');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'asignatura', 'school subject');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'excursin', 'trip, excursion');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'camarera', 'waitress');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'informtica', 'ICT');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'mochila', 'rucksack, school bag');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (f)', 'bicicleta, bici', 'bicycle, bike');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (fpl)', 'matemticas', 'maths');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'club', 'club');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'examen', 'exam');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'Internet', 'internet');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'uniforme', 'uniform');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'da', 'day');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'pas', 'country');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'mundo', 'world');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'trabajo', 'work, job, effort');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'seor', 'Mr., man, Sir, gentleman');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'arte', 'art');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'amigo', 'friend');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'libro', 'book');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'estudio', 'study, learning, studio');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'campo', 'countryside, pitch, field');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'juego', 'game');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'equipo', 'team, equipment');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'proyecto', 'project, plan');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'papel', 'paper, role, part');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'sueo', 'dream, sleep');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'mercado', 'market');