SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'premio', 'prize, reward, award');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'museo', 'museum');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'verano', 'summer');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'ejercicio', 'exercise');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'peligro', 'danger');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'vdeo', 'video');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'novio', 'boyfriend, groom');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'pan', 'bread');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'vino', 'wine');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'parque', 'park');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'concierto', 'concert');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'ftbol', 'football');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'zapato', 'shoe');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'deporte', 'sport');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'pjaro', 'bird');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'espectculo', 'show, spectacle');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'vestido', 'dress');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'dibujo', 'drawing, art');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'plato', 'plate, dish');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'invierno', 'winter');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'pantaln', 'trousers');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'regalo', 'present, gift');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'huevo', 'egg');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'azcar', 'sugar');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'baile', 'dance');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'mvil', 'mobile phone');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'concurso', 'competition, quiz');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'estadio', 'stadium');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'ordenador', 'computer');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'restaurante', 'restaurant');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'pescado', 'fish');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'pollo', 'chicken');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'tomate', 'tomato');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'teclado', 'keyboard');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'baloncesto', 'basketball');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'bocadillo', 'sandwich');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'camarero', 'waiter');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'caramelo', 'sweet');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'gimnasio', 'gym');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'jamn', 'ham');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m)', 'flamenco', 'flamenco (dance/music from the south of Spain)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'ver', '(to) see, watch | seeing, watching');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'veo', '(I) see | (I) am seeing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'vea', '(I, she, he, it, one) used to see, used to watch | (I, she, he, it, one) was seeing, was watching | (you (sing formal)) used to see, used to watch | (you (sing formal)) were seeing, were watching');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'veas', '(you (sing informal)) used to see, used to watch | were seeing, were watching');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'llamar; llamarse', '(to) call, name | calling, naming; (to) be called | being called');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'perder; perderse', '(to) lose, miss | losing, missing; (to) get lost | getting lost');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'escribir', '(to) write | writing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'leer', '(to) read | reading');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'ganar', '(to) win, earn | winning, earning');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'tocar', '(to) touch, play (instrument) | touching, playing (instrument)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'correr', '(to) run | running');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'comer', '(to) eat | eating');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'levantar; levantarse', '(to) raise | raising; (to) get up | getting up');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'jugar', '(to) play (sport/game) | playing (sport/game)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'juego', '(I) play | (I) am playing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'juegas', '(you) play | (you) are playing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'juega | ijuega!', '(she, he, it, one) plays | (she, he, it, one) is playing | (you (sing formal)) play | Play! (you (sing informal))');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'juegan', '(they) play | (they) are playing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'comprar', '(to) buy, purchase | buying, purchasing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'pagar', '(to) pay (for) | paying (for)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'dormir; dormirse', '(to) sleep | sleeping; (to) fall asleep | falling asleep');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'aprender', '(to) learn | learning');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'bajar', '(to) go down, get off, download, lower  | going down, getting off, downloading, lowering');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'participar', '(to) participate | participating');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'cantar', '(to) sing | singing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'costar', '(to) cost, be hard | costing, being hard');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'invitar', '(to) invite | inviting');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'celebrar; celebrarse', '(to) celebrate | celebrating; (to) hold (an event) | holding (an event)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'viajar', '(to) travel | travelling');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'probar', '(to) taste, try | tasting, trying');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'organizar', '(to) organise | organising');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'beber', '(to) drink | drinking');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'recomendar', '(to) recommend I recommending');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'aprobar', '(to) pass (test) I passing (test)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'bailar', '(to) dance I dancing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'pintar; pintarse', '(to) paint I painting; (to) put on makeup | putting on makeup');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'montar', '(to) ride, set up I riding, setting up');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'grabar', '(to) record I recording');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'doler', '(to) hurt, be painful I hurting, being painful');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'descansar', '(to) rest, relax I resting, relaxing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'gastar', '(to) spend (money) I spending (money)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'reservar', '(to) book, reserve | booking, reserving');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'cenar', '(to) have dinner, tea (evening meal) | having dinner, tea (evening meal)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'ahorrar', '(to) save (time, money) | saving (time, money)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'nadar', '(to) swim | swimming');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'v', 'entrenar; entrenarse', '(to) train | training; (to) train, go training | training, going training');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m/f)', 'jugador', 'player');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m/f)', 'cliente', 'client, customer');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (m/f)', 'cantante', 'singer');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'grave', 'serious, grave');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'social', 'social');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'nuevo', 'new, another (pre-noun), new, newly-made (post-noun)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'pblico', 'public, audience');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'joven', 'young');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'antiguo', 'former (pre-noun), old, ancient (pre and post-noun)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'pobre', 'poor, unfortunate (pre-noun), without money (post-noun)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'actual', 'current');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'ingls', 'English');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'adj', 'responsable', 'responsible');