SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'restaurante', 'restaurant');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'paro', 'unemployment, strike');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'otoo', 'autumn');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'autobs', 'bus');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'gimnasio', 'gym');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'medioambiente/medio ambiente', 'environment, natural world');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m)', 'supermercado', 'supermarket');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (mpl)', 'servicios', 'toilets');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'prep', 'entre', 'between, among');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'prep', 'debajo', 'underneath, below');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'dar', '(to) give | giving');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'deber', '(to) have to, must | having to');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'vivir', '(to) live | living');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'trabajar', '(to) work | working');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'perder; perderse', '(to) lose, miss | losing, missing; (to) get lost | getting lost');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'morir', '(to) die | dying');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'usar', '(to) use | using');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'ayudar', '(to) help | helping');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'vender', '(to) sell |selling');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'participar', '(to) participate | participating');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'construir', '(to) build |building');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'aumentar', '(to) increase | increasing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'tirar', '(to) throw, pull | throwing, pulling');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'salvar', '(to) save, rescue | saving, rescuing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'visitar', '(to) visit | visiting');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'separar; separarse', '(to) separate I separating; (to) separate (of a couple) | separating (of a couple)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'recoger', '(to) pick up, collect, tidy up | picking up, collecting, tidying up');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'mejorar', '(to) improve, make better | improving, making better');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'reducir', '(to) reduce | reducing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'causar', '(to) cause | causing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'conducir', '(to) drive | driving');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'coger', '(to) take, take hold of, catch | taking, taking hold of, catching');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'organizar', '(to) organise | organising');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'proteger', '(to) protect | protecting');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'respetar', '(to) respect I respecting');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'describir', '(to) describe I describing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'robar', '(to) rob, steal I robbing, stealing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'destruir', '(to) destroy, ruin I destroying, ruining');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'encender', '(to) turn on I turning on');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'comparar', '(to) compare I comparing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'limpiar', '(to) clean I cleaning');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'apagar', '(to) turn off, extinguish I turning off, extinguishing');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'votar', '(to) vote I voting');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'llover', '(to) rain I raining');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'contaminar', '(to) pollute, contaminate | polluting, contaminating');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'v', 'reciclar', '(to) recycle | recycling');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m/f)', 'joven', 'teenager, young person');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m/f)', 'mar', 'sea');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m/f)', 'vecino', 'neighbour');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m/f)', 'cientfico', 'scientist');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Environment and where people live', 'n (m/f)', 'turista', 'tourist');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'social', 'social');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'seguro', 'safe, sure, secure');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'fuerte', 'strong');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'fcil', 'easy');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'popular', 'popular');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'moderno', 'modern');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'directo', 'direct, straight');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'elctrico', 'electric');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'peligroso', 'dangerous');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'dbil', 'weak');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'caro', 'expensive');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'gratis', 'free (of charge)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'adj', 'online', 'online');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'mwp', 'medios de comunicacin', 'media');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'msica', 'music');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'imagen', 'image, picture');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'accin', 'action, act');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'serie', 'series');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'cultura', 'culture');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'comunidad', 'community');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'pelcula', 'film, movie');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'pgina', 'page');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'salud', 'health');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'carta', 'letter, menu');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'direccin', 'address, direction');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'energa', 'energy, power');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'red (Red)', 'network (Internet), net (fishing)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'tele, televisin', 'TV, television');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'foto', 'photo, picture');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'cmara', 'camera');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'conversacin', 'conversation');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'app', 'app');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'tecnologa', 'technology');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'escena', 'scene (of film), stage');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'marca', 'make, brand');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'compra(s)', 'shopping');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'pantalla', 'screen, monitor');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'informtica', 'ICT');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (f)', 'tableta', 'tablet (eg. ipad)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'euro', 'euro');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'Internet', 'internet');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'nombre', 'name');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'programa', 'programme');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'artculo', 'article, product, item');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'sitio (web)', 'place, site (website)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'resultado', 'result');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'contacto', 'contact');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'mensaje', 'message');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Media and technology', 'n (m)', 'telfono', 'phone, telephone');