SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'alegra', 'joy, happiness');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'religin', 'religion');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'reina', 'queen');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'boda', 'wedding');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'guitarra', 'guitar');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'celebracin', 'celebration');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'Navidad', 'Christmas');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'mezquita', 'mosque');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'Nochebuena', 'Christmas Eve');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'sinagoga', 'synagogue');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'uva', 'grape');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'corrida', 'bullfight');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'Nochevieja', 'New Year''s Eve');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'paella', 'paella (dish usually of rice and seafood)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (f)', 'Tomatina', 'Spanish tomato festival');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (fpl)', 'tapas', 'small dishes of food, bar snacks');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (fpl)', 'Las Fallas', 'Valencian celebration involving burning of papier mch models');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'animal', 'animal');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'caf', 'coffee, cafe');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'nombre', 'name');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'pas', 'country');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'mundo', 'world');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'arte', 'art');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'paso', 'step, pace, religious image carried in Holy Week processions');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'traje', 'suit, costume');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'juego', 'game');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'sol', 'sun');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'inters', 'interest');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'aire', 'air');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'santo', 'saint, saint''s day');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'mercado', 'market');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'viaje', 'trip, journey');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'teatro', 'theatre, drama');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'rey', 'king');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'riesgo', 'risk');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'fuego', 'fire');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'caballo', 'horse');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'puesto', 'post, position, stall (market)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'puerto', 'port, harbour');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'habitante', 'local (person), inhabitant');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'matrimonio', 'marriage');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'peligro', 'danger');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'vino', 'wine');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'concierto', 'concert');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'vestido', 'dress');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'plato', 'plate, dish');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'regalo', 'present, gift');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'templo', 'temple');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'baile', 'dance');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'toro', 'bull');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'cumpleaos', 'birthday');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'tomate', 'tomato');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'desfile', 'procession, parade');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'caramelo', 'sweet');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'disfraz', 'costume, fancy dress');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m)', 'flamenco', 'flamenco (dance/music from the south of Spain)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (mpl)', 'Sanfermines', 'festival in Pamplona involving running of the bulls');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'pasar', '(to) pass, spend (time), happen I  passing, spending (time), happening');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'recibir', '(to) receive | receiving');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'comer', '(to) eat | eating');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'descubrir', '(to) discover | discovering');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'compartir', '(to) share | sharing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'participar', '(to) participate | participating');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'tirar', '(to) throw, pull | throwing, pulling');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'vestir; vestirse', '(to) dress | dressing; (to) get dressed | getting dressed');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'cantar', '(to) sing | singing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'invitar', '(to) invite | inviting');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'celebrar; celebrarse', '(to) celebrate | celebrating; (to) hold (an event) | holding (an event)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'viajar', '(to) travel | travelling');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'bailar', '(to) dance I dancing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'pintar; pintarse', '(to) paint I painting; (to) put on makeup | putting on makeup');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'besar', '(to) kiss I kissing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'v', 'reservar', '(to) book, reserve | booking, reserving');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m/f)', 'mar', 'sea');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Customs, festivals and celebrations', 'n (m/f)', 'artista', 'artist, performer');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'adj', 'social', 'social');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'adj', 'rico', 'rich, wealthy, tasty');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'adj', 'fsico', 'physical');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'adj', 'clsico', 'classic, classical');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'adj', 'musical', 'musical');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'adj', 'activo', 'active');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'adj', 'artstico', 'artistic');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'adj', 'dulce', 'sweet');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'adj', 'deportivo', 'sporty, sports');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'adj', 'gracioso', 'funny');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'adj', 'bienvenido', 'welcome');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'adj', 'gratis', 'free (of charge)');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'mwp', 'patatas fritas', 'chips, fries');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'mwp', 'tomar el sol', '(to) sunbathe | sunbathing');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'mwp', 'medios de comunicacin', 'media');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'mwp', 'pasarlo bien/mal', 'to have a good/bad time');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'mwp', 'centro comercial', 'shopping centre');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'mwp', 'al aire libre', 'in the open air, outdoors');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'mwp', 'parque temtico', 'theme park');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'mwp', 'dar un paseo', '(to) go for a walk, stroll | going for a walk, stroll');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'cuenta', 'bill, account');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'agua', 'water');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'familia', 'family');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'relacin', 'relationship');
SELECT import_gcse_vocabulary_simple('Popular culture', 'Free time activities', 'n (f)', 'msica', 'music');