SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'temperatura', 'temperature');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'estacin', 'station, season (of the year)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'montaa', 'mountain');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'playa', 'beach');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'copa', 'cup, glass');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'tienda', 'shop, tent');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'bolsa', 'bag');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'arquitectura', 'architecture');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'compra(s)', 'shopping');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'carretera', 'road');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'identidad', 'identity');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'fruta', 'fruit');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'tarjeta', 'written card, bank card');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'cena', 'dinner, evening meal');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'vacaciones; de vacaciones', 'holidays; on holiday');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'primavera', 'spring');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'bebida', 'drink');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'geografa', 'geography');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'recepcin', 'reception');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'maleta', 'suitcase');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'piscina', 'swimming pool');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'excursin', 'trip, excursion');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'camarera', 'waitress');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'mezquita', 'mosque');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'mochila', 'rucksack, school bag');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'sinagoga', 'synagogue');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'corrida', 'bullfight');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'paella', 'paella (dish usually of rice and seafood)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'Espaa', 'Spain');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'Sudamrica', 'South America');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (f)', 'bicicleta, bici', 'bicycle, bike');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (fpl)', 'tapas', 'small dishes of food, bar snacks');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'caf', 'coffee, cafe');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'camping', 'camp site, camping');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'euro', 'euro');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'este', 'east');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'pas', 'country');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'mundo', 'world');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'campo', 'countryside, pitch, field');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'pie; a pie', 'foot; on foot');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'sol', 'sun');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'espacio', 'space, room');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'mercado', 'market');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'ro', 'river');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'viaje', 'trip, journey');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'peso', 'weight, peso (currency)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'precio', 'price, cost, value');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'extranjero', 'abroad, foreigner (m)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'recuerdo', 'memory, souvenir');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'metro', 'underground, tube, metro, metre');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'viento', 'wind');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'edificio', 'building');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'piso', 'flat, apartment, floor (of building)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'barrio', 'neighborhood, district');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'calor', 'heat, hot');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'grado', 'degree (temperature)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'puerto', 'port, harbour');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'museo', 'museum');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'habitante', 'local (person), inhabitant');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'verano', 'summer');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'idioma', 'language');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'hotel', 'hotel');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'coche', 'car');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'jardn', 'garden');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'bao', 'bathroom');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'pan', 'bread');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'vino', 'wine');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'barco', 'boat, ship');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'avin', 'plane, aeroplane');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'transporte', 'transport');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'bosque', 'forest, wood');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'tren', 'train');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'kilmetro', 'kilometer');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'plano', 'map');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'espectculo', 'show, spectacle');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'clima', 'climate');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'paisaje', 'landscape');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'vuelo', 'flight');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'plato', 'plate, dish');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'invierno', 'winter');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'templo', 'temple');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'trfico', 'traffic');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'dormitorio', 'bedroom');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'oeste', 'west');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'aeropuerto', 'airport');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'castillo', 'castle');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'restaurante', 'restaurant');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'billete', 'ticket (for transport)');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'desayuno', 'breakfast');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'pescado', 'fish');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'otoo', 'autumn');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'pollo', 'chicken');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'autobs', 'bus');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'desfile', 'procession, parade');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'alojamiento', 'accommodation');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'camarero', 'waiter');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'jamn', 'ham');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'n (m)', 'ayuntamiento', 'Spanish town council, city council, town hall');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'buscar', '(to) look for, fetch | looking for, fetching');
SELECT import_gcse_vocabulary_simple('Communication and the world around us', 'Travel and tourism', 'v', 'perder; perderse', '(to) lose, miss | losing, missing; (to) get lost | getting lost');