SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'resultado', 'result');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'autor', 'writer, author');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'viaje', 'trip, journey');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'miembro', 'member');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'esfuerzo', 'effort');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'teatro', 'theatre, drama');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'colegio', '(secondary) school');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'negocio', 'business');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'xito', 'success');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'banco', '(financial) bank, bench');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'extranjero', 'abroad, foreigner (m)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'apoyo', 'support, backing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'edificio', 'building');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'alumno', 'student, pupil');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'error', 'error, mistake');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'ejrcito', 'army');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'consejo', '(piece of) advice');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'peridico', 'newspaper');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'hospital', 'hospital');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'premio', 'prize, reward, award');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'respeto', 'respect, regard');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'museo', 'museum');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'septiembre', 'September');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'idioma', 'language');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'patio', 'yard, playground');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'dueo', 'owner, landlord (m)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'barco', 'boat, ship');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'avin', 'plane, aeroplane');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'empleo', 'work, job, occupation');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'ftbol', 'football');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'zapato', 'shoe');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'actor', 'actor (m)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'instituto', 'secondary school');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'comportamiento', 'behaviour');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'espectculo', 'show, spectacle');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'correo (electrnico)', 'mail, post (email)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'puente', 'bridge, long weekend');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'dibujo', 'drawing, art');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'vuelo', 'flight');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'empleado', 'employee');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'pantaln', 'trousers');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'salario', 'salary');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'concurso', 'competition, quiz');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'deberes', 'homework');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'horario', 'timetable, schedule');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'estadio', 'stadium');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'ordenador', 'computer');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'enfermero', 'nurse');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'paro', 'unemployment, strike');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'autobs', 'bus');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'estrs', 'stress');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'acoso', 'bullying');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'bolgrafo', 'pen');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'camarero', 'waiter');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'cuidador', 'carer');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'peluquero', 'hairdresser');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'recreo', 'break (at school)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (m)', 'Bachillerato', 'Baccalaureate (equivalent to A levels)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'n (mpl)', 'servicios', 'toilets');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'llamar; llamarse', '(to) call, name | calling, naming; (to) be called | being called');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'trabajar', '(to) work | working');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'buscar', '(to) look for, fetch | looking for, fetching');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'escribir', '(to) write | writing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'leer', '(to) read | reading');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'pedir', '(to) ask for | asking for');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'permitir; permitirse', '(to) allow, permit | allowing, permitting; (to) afford | affording');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'sacar', '(to) take out, get, obtain | taking out, getting, obtaining');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'servir', '(to) serve | serving');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'tocar', '(to) touch, play (instrument) | touching, playing (instrument)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'estudiar', '(to) study | studying');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'comer', '(to) eat | eating');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'jugar', '(to) play (sport/game) | playing (sport/game)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'juego', '(I) play | (I) am playing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'juegas', '(you) play | (you) are playing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'juega | ijuega!', '(she, he, it, one) plays | (she, he, it, one) is playing | (you (sing formal)) play | Play! (you (sing informal))');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'juegan', '(they) play | (they) are playing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'continuar', '(to) continue |continuing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'aprender', '(to) learn | learning');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'aceptar', '(to) accept | accepting');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'vender', '(to) sell |selling');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'mandar', '(to) send, order | sending, ordering');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'participar', '(to) participate | participating');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'construir', '(to) build |building');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'ensear', '(to) teach, show| teaching, showing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'apoyar', '(to) support | supporting');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'gritar', '(to) shout | shouting');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'enviar', '(to) send | sending');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'cantar', '(to) sing | singing');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'mejorar', '(to) improve, make better | improving, making better');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'viajar', '(to) travel | travelling');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'organizar', '(to) organise | organising');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'respetar', '(to) respect I respecting');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'aprobar', '(to) pass (test) I passing (test)');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'soar', '(to) dream I dreaming');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'comunicar', '(to) communicate  I  communicating');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'pintar; pintarse', '(to) paint I painting; (to) put on makeup | putting on makeup');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'callarse', '(to) be quiet, quieten down I being quiet, quietening down');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'grabar', '(to) record I recording');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'votar', '(to) vote I voting');
SELECT import_gcse_vocabulary_simple('People and lifestyle', 'Education and work', 'v', 'pelearse', '(to) fight (physically) I fighting (physically)');